### PR TITLE
feat: add public key

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- Add public key
- Add `.gitignore`

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [x] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@theofficialgman does this look right?

**Comment by theofficialgman** [comment]
it would be better for the public key to live in the `gh-pages` branch since users will be downloading that public key.
downloading from github pages is generally better than raw.githubusercontent.com which is what they would have to do if it were only in the master branch

**Comment by ReenigneArcher** [comment]
Okay. I'll have the workflow copy this over to `gh-pages` once it's ready.

**Comment by theofficialgman** [comment]
sure. the workflow works as it is now if you have the pages setting set to
image
but feel free to create a custom actions based deployment if you would rather do so for other reasons

**Pull request merged**
